services:
  zomboid:
    image: ghcr.io/tibuski/project-zomboid-server-docker:latest
    container_name: project-zomboid
    restart: unless-stopped
    stop_grace_period: 120s
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
    env_file:
      - .env
    volumes:
      - ./data:/home/steam/Zomboid
      - ./server-files:/home/steam/pzserver
      - ./backups:/home/steam/Zomboid/backups
